import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         {/* Header */}
        <div className="flex justify-center items-center bg-gray-100">
          <header className="flex items-center justify-between px-6 py-4 bg-gray-100">

         
            <nav className="flex items-center gap-6">
              <button className="text-gray-600 hover:text-orange-500 transition-colors font-medium">
              <Link href="/pg/edit">Editor</Link>  
              </button>
              <button className="text-gray-600 hover:text-orange-500 transition-colors font-medium">Settings</button>
              <button className="text-gray-600 hover:text-orange-500 transition-colors font-medium">Help</button>
            </nav>
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
